// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMLUoOENeFF6P_pW07VWismR4Z5TJY79U',
    appId: '1:760589109334:web:490c24b5cbb9269a1c93f7',
    messagingSenderId: '760589109334',
    projectId: 'damageassessor-a5748',
    authDomain: 'damageassessor-a5748.firebaseapp.com',
    storageBucket: 'damageassessor-a5748.firebasestorage.app',
    measurementId: 'G-922VK22800',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMmcWNfbiCD3CdHVkgDH0CGYGsapKGLjQ',
    appId: '1:760589109334:android:96fc0532a41ba1b71c93f7',
    messagingSenderId: '760589109334',
    projectId: 'damageassessor-a5748',
    storageBucket: 'damageassessor-a5748.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBgJCqIWKlPBD6wA8BqdfJkdUZ8Np8Fc',
    appId: '1:760589109334:ios:c468ff24b25e95f31c93f7',
    messagingSenderId: '760589109334',
    projectId: 'damageassessor-a5748',
    storageBucket: 'damageassessor-a5748.firebasestorage.app',
    iosBundleId: 'com.example.damageAssessor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBgJCqIWKlPBD6wA8BqdfJkdUZ8Np8Fc',
    appId: '1:760589109334:ios:c468ff24b25e95f31c93f7',
    messagingSenderId: '760589109334',
    projectId: 'damageassessor-a5748',
    storageBucket: 'damageassessor-a5748.firebasestorage.app',
    iosBundleId: 'com.example.damageAssessor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMLUoOENeFF6P_pW07VWismR4Z5TJY79U',
    appId: '1:760589109334:web:f340d0eac044de431c93f7',
    messagingSenderId: '760589109334',
    projectId: 'damageassessor-a5748',
    authDomain: 'damageassessor-a5748.firebaseapp.com',
    storageBucket: 'damageassessor-a5748.firebasestorage.app',
    measurementId: 'G-GDTMELNBCP',
  );
}
